language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - '7' # or '7.0'
  - hhvm
  - nightly
matrix:
  allow_failures:
    - php: nightly
install:
  - composer require satooshi/php-coveralls:~0.6@stable
  - composer self-update
  - composer install
before_script:
  - mkdir -p build/logs
script: ./runtests.sh
after_script:
  - php ./vendor/bin/coveralls -v
