language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - '7' # or '7.0'
  - hhvm
  - nightly
install:
  - composer require satooshi/php-coveralls:~0.6@stable
  - composer self-update
  - composer install
before_script:
  - mkdir -p build/logs
script: phpunit --configuration ./phpunit.xml tests/automated
after_script:
  - php ./tools/coveralls -v
