language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - '7' # or '7.0'
  - hhvm
  - nightly
install:
  - composer install --dev
script: phpunit --configuration ./phpunit.xml tests/automated
after_script:
  - php vendor/bin/coveralls -v
